### ISSUE TITLE
No best permissions returned

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1815]
> An example request where only "all_permissions" is returned would be: https://api.openaccessbutton.org/permissions?doi=10.1055/s-0030-1263175

I think everything that has a response should return a best permission. So, seems like a problem here.

**Comment by markmacgillivray** [comment]
The code currently states if there are any permissions found, score them and sort by score, then check through them all, and pick the first (highest scored) one that either does NOT have a provenance enforcement date OR we don't know the published date OR we DO know the published date and it is greater than the provenance date. We then also check through ROR ones if appropriate.

So it is possible that there may not be a best_permission at all, if all the permissions we found have provenance enforcement dates, and we know the published date, and it is before the provenance enforcement date.

**Comment by markmacgillivray** [comment]
Also, I've mentioned before I'm not a fan of the "best_permission" / "all_permissions" separation. What is the requirement for it? Couldn't we just return a sorted list of all the permission we did find?

**Comment by JosephMcArthur** [comment]
Ah, that makes sense. I think likely what we need to do is introduce some logic that says:

If there is some permissions record, BUT, the requirements for it are not met, then the best permission should return our "permissions required" response.

I think this could be done via new records in the database, or logic in the API responses.

Let me have a think, and I'll circle back.

> Also, I've mentioned before I'm not a fan of the "best_permission" / "all_permissions" separation. What is the requirement for it? Couldn't we just return a sorted list of all the permission we did find?

- [ ] Will respond to this later, given it's not a "fix".

**Comment by JosephMcArthur** [comment]
@natalianorori where there is a `Enforcement Date` present in policies, can you make a `permissions required` policy for that entity? 

That should resolve this issue without code changes, and I think makes the most sense. Most publisher policies are retroactive, and only a dozen or so aren't.

That would mean, for this article, we'd show a permissions required response which would in fact be the correct response.

**Comment by natalianorori** [comment]
I have made this change on our data, should be updated in the API soon, will monitor and let you know when the change is live.  @JosephMcArthur

**Comment by JosephMcArthur** [comment]
@natalianorori can you retry this & update the issue accordingly.

**Comment by natalianorori** [comment]
Retried but we are still getting "All permissions".  I changed the "last updated date" again with no luck.
