### ISSUE TITLE
DOIs provided by zenodo don't resolve

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1832]
**Describe the bug**

DOIs provided by zenodo in deposit emails don't resolve

**To Reproduce**

See `Successful Deposit: 10.2139/ssrn.3667298`

**Expected behavior**

The given DOI should resolve.

**Proposed Fix (if available)**

I think the issue is that we pass the DOI to the deposit via the DOI field here:

![image](https://user-images.githubusercontent.com/4953703/133826581-9eb8b3e9-03ac-4031-8ba3-d5243c72d2d9.png)

This stops Zenodo minting a DOI for this deposit, and that DOI is desirable. It also leads to the DOI for the published version being used in the citation Zenodo provides:

![image](https://user-images.githubusercontent.com/4953703/133826786-8fa65ada-e63f-4743-8cc6-d0a617d80d22.png)

Instead I think we should provide the DOI as a part of this section. 

![image](https://user-images.githubusercontent.com/4953703/133826721-771f6573-8706-4e6a-ac21-05f870d6aae0.png)

Likely it's "is a new version of this upload".

My only concern doing this is if unpaywall will still pick up the article correctly. I expect so but I'm not sure.

**Comment by markmacgillivray** [comment]
We have specific code in deposit already that does not match what you asked for above. That's OK, I can change it, but just letting you know in case there was a reason you've forgotten about. 

What we currently do is, if we know the DOI, we search zenodo. If it's already in zenodo then we don't upload again unless it is an admin upload or we're on dev. In those cases we provide the DOI as a related_identifier and we call it isPreviousVersionOf if it is a preprint or postprint or AAM, otherwise we call it isIdenticalTo.

However if we know the DOI and we search zenodo and it is NOT in zenodo, then yes we explicitly do provide the DOI as metadata, meaning we are intentionally not using the prereserved zenodo DOIs in this case. So at some point in the past you specifically wanted this. Since we provide a DOI in the metadata, I imagine that zenodo never bothers to register the reserved DOIs.

So, as long as you don't mind the change, then yeah I can easily make it so that DOIs are always provided by us as related, regardless of whether or not we find them in Zenodo.

**Comment by JosephMcArthur** [comment]
This change still sounds good. Can you ask Richard if they'd still be able to match papers to the published version after this change.

**Comment by markmacgillivray** [comment]
Done on old dev and have emailed Richard to see what they think. Code copy-pasta'd into old live as well, but commented out until ready to go. New API system already has this change in it so whenever we switch over this will already be in place as well. Once I hear back from Richard I will either enable on old live or will report back here if the response is negative.

**Comment by markmacgillivray** [comment]
Richard says he doesn't think they match the related_identifiers field directly but it may match by title/authors anyway. It's not exactly clear yet whether they're searching for the DOI or scraping through the data dumps, and what they're scraping for and where. He's asked when we might want to enable this so they could do an upgrade. I've said we could do any time and suggested we just go ahead and see how it goes. We can always switch back and wait for them to change if that's a preferable consequence for you. I won't change it yet, will wait to see what his response is.

**Comment by JosephMcArthur** [comment]
Happy to go ahead and make the change and wait and see. Title/author match
should be enough for them.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
@markmacgillivray I'm still seeing problems with this, such as on `Successful Deposit: 10.1111/nph.17611`. Can you look into it?

**Comment by markmacgillivray** [comment]
It appears that this change had not yet been put into effect on the old live system, but the issue had been closed. I've now changed on the old live system.

**Comment by markmacgillivray** [comment]
I've done a fair bit of investigating this over the last few weeks while doing other deposit things and reviewing zenodo API stuff. I can't find any further reason for why we would be getting zenodo DOIs created that just don't go anywhere. I can't find a reason at our end. Maybe there's just a delay in zenodo making those DOIs live? (Which would not be very useful). We should at least now be creating less unnecessary ones anyway, by using the related_identifier approach as above. I'm not sure what else to do about this one, we could discuss and either close or just keep an eye on in the new system and see what happens.

**Comment by JosephMcArthur** [comment]
Can you please speak to the Zenodo help desk about this, stating what investigations we've already done to make getting an answer from them easier.

**Comment by JosephMcArthur** [comment]
Is it useful to know the most recent deposit we made had working zenodo DOIs: https://zenodo.org/record/5831466?

**Comment by markmacgillivray** [comment]
I believe this issue can be closed now.

**Comment by markmacgillivray** [comment]
Just a comment here to say nothing changed, feel free to close if you are happy with this.
